### ISSUE TITLE
No longer working on Android marshmallow devices

### ISSUE THREAD

**Issue by jazarja** [mderazon/node-deeplink#10]
I just testing my deeplink implementation, that working fine on Android 4 and Android 5, but found the deeplink is not working properly on Nexus 5 with Android marshmallow. It seems the redirection does not work anymore on Android 6.

**Comment by mderazon** [comment]
Let me check and find the problem

**Comment by mderazon** [comment]
@jazarja can you tell me exactly what doesn't work ?
It seems to be working fine on my device with 6.0 installed

**Comment by jazarja** [comment]
My mistake, it seems the issue related only to Google Chrome version 45 (Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Safari/537.36) that supplied by Android M on Nexus 5.

So I have a deep link (eg: http://telepon.id/p/00000001), this link working properly (even on Android M) when I click the link from other app (SMS or messenger). But when I copy and paste this link to google chrome directly, the deep link redirection seems not working (does not open the google play).

I also find this strange chrome behavior on Chrome 45 in other android devices  (Android 5 & Android 4)

**Comment by mderazon** [comment]
I think I see what you mean. Tried to look for any breaking change in chrome for Android but couldn't find anything. Are you able to find anything?
Looks like the line
```
document.location = urls.android_intent
```
Doesn't launch anymore.

**Comment by mderazon** [comment]
@jazarja this is an expected behaviour. It was added by chrome team as a security measure. The idea is that they don't want websites to "hijack" the users to another website / app without their consent. So the deeplink works only if the users made an active decision like opening a link. 

You can read about it here
- https://code.google.com/p/chromium/issues/detail?id=459156
- http://blog.tapstream.com/google-changes-chrome-to-prevent-abusive/
