### ISSUE TITLE
Why sending url in params is require ?

### ISSUE THREAD

**Issue by stevenlalalab** [mderazon/node-deeplink#19]
Hello, 

I dont' understand why should I send url in params while doing a get request to my server. Here's my code for example.

```
app.get('/deeplink', deeplink({
  fallback: 'https://www.my-site.com',
  android_package_name: 'com.my-site.gramlopa',
  ios_store_link: 'https://itunes.apple.com/us/app/my-site'
}))
```

Why should I send url in params ? 

> http://my-site.com/deeplink?url=cups%3A%2F%2Fmain

it said in the documentation 

> so when users will open it the app will open with app://account deeplink or the users will be redirected to download the app in case they don't have it.

So does account should be the apple id of the user in case of the user is using an Apple device and doesn't have the app ?

Thanks

**Comment by mderazon** [comment]
The url you are sending in query param is the deeplink url you want the app to open.

So for example 
```
http://my-site.com/deeplink?url=cups%3A%2F%2Fmain
```
Will open `cups://main` in the mobile app. Your app needs to register this scheme in order to open these links in the app.

The url is mandatory, otherwise how would the javascript code running in the middleware know which deeplink in your app to open ?
